### ISSUE TITLE
Iconsistance when packaging

### ISSUE THREAD

**Issue by grimpy** [complexlogic/big-launcher#17]
First of all thanks for the package I've been using it for over a year now and before it flex-launcher.

Since every now and then this binary breaks cause my system has updates and I need to recompile it to fix it, I decided to package it for ArchLinux your can find my package files here https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=big-launcher-git

I decided to use the name 'big-launcher' for the name as the package so for constancy also make the binary and the project-name called big-launcher.

I wonder if this makes sense to you to change this in your default CMakelists.txt file aswell?

**Comment by complexlogic** [comment]
Sure, that makes sense. And thanks for packaging the project.
