### ISSUE TITLE
Xbox Controller Won't Wake Up From Sleep

### ISSUE THREAD

**Issue by n-depinto** [complexlogic/big-launcher#9]
I have noticed an issue while using the windows build of Big Launcher with a Wireless Xbox One controller. (using the USB Xbox Wireless Dongle)

If Big Launcher is running and the wireless Xbox controller automatically powers off, (as it will when the controller is not used after a set period of time) the controller will not be able to turn back on. When you press the guide button, as you would normally to turn on the controller, the guide button will  flash on for a second before immediately turning off again. This behavior only appears while Big Launcher is running. If I close Big Launcher and then restart it, the controller will be able to turn on as normal.

The behavior also appears if Big Launcher is running in the background. For instance, if a game is running in the foreground and the controller powers off automatically, the controller will not be able to turn back on until I restart (or close) Big Launcher in the background.

I hope this helps. Thanks for all your work!

**Comment by complexlogic** [comment]
This was actually an issue in SDL that has since been fixed. The build has been updated for the latest version and everything should be working now.
